[features]
seeds = false
skip-lint = false
[programs.testnet]
solei = "8jXvG9wdujAedJ3cae4NyJkQseY6ziQrr85ZKVzh4u2o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/Users/chouchou/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
